apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    component: database
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    component: database
spec:
  containers:
    - name: database
      image: postgres
      env:
        - name: POSTGRES_DB
          value: api-db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
