apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
  - ../../base
resources:
  - database.yaml
patchesStrategicMerge:
  - patches/add-config.yaml
configMapGenerator:
  - name: hello-linear-config
    files:
      - config.yaml
