apiVersion: v1
kind: Service
metadata:
  name: hello-linear
spec:
  type: LoadBalancer
  selector:
    app: hello-linear
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
